import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import LenisSetup from "./Components/LenisSetup/LenisSetup";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisSetup>
          {children}
        </LenisSetup>
      </body>

      <Script
        async type="module"
        src="https://cdn.jsdelivr.net/npm/@finsweet/attributes@2/attributes.js"
        fs-scrolldisable
      ></Script>
    </html>
  );
}
